version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=6000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BREVO_SENDER_EMAIL=${BREVO_SENDER_EMAIL}
      - BREVO_SENDER_NAME=${BREVO_SENDER_NAME:-No-Reply}
      - EMAIL_DRY_RUN=${EMAIL_DRY_RUN:-true}
    ports:
      - "6000:6000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - BACKEND_URL=http://localhost:6000
    ports:
      - "8501:8501"
    depends_on:
      - backend


